### ISSUE TITLE
include elastic curator as part of elasticsearch chart

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-charts#63] opened 2017-02-09 17:07 UTC
as discussed in #48 we should be using curator with some sane defaults for length of time to keep indexes open, around and how often to run cleanup operations.

**Comment by coffeepac** [comment] 2017-07-26 21:28
@leahnp take a look!  put back to p2 if needed.

**Comment by DStorck** [comment] 2017-10-06 23:15
moved to issues. ( dupe of https://github.com/samsung-cnct/elasticsearch-kubernetes/issues/8)

**Closed by DStorck** 2017-10-06 23:15 UTC
Labels: feature request, k2-charts, priority-p3
